name: Codecov coverage workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Codecov coverage
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' # Use the desired Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests and collect coverage
        run: flutter test --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Make sure to set CODECOV_TOKEN as a secret in your repository
